- name: ensure all template files are rendered
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: 'templates/namespace.yaml.j2', dest: '{{ dst_template_path }}/{{ cluster_name }}-namespace.yaml' }
    - { src: 'templates/channel.yaml.j2', dest: '{{ dst_template_path }}/{{ cluster_name }}-channel.yaml' }
    - { src: 'templates/application.yaml.j2', dest: '{{ dst_template_path }}/{{ cluster_name }}-application.yaml' }
    - { src: 'templates/placementrule.yaml.j2', dest: '{{ dst_template_path }}/{{ cluster_name }}-placementrule.yaml' }
    - { src: 'templates/subscription.yaml.j2', dest: '{{ dst_template_path }}/{{ cluster_name }}-subscription.yaml' }

- name: List all files in the directory
  find:
    path: "{{ dst_template_path }}"
  register: _result

- name: Write Kustomisation file
  template:
    src: 'templates/kustomization.yaml.j2'
    dest: '{{ dst_template_path }}/kustomization.yaml'
